"""modified tables

Revision ID: a154e8a5ad10
Revises: 
Create Date: 2026-08-26 16:50:42.190705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a154e8a5ad10'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_reservation_seat', 'reservation_seats', ['reservation_id', 'seat_id'])
    op.create_foreign_key(None, 'seats', 'halls', ['hall_id'], ['hall_id'])
    op.create_foreign_key(None, 'showtimes', 'halls', ['hall_id'], ['hall_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'showtimes', type_='foreignkey')
    op.drop_constraint(None, 'seats', type_='foreignkey')
    op.drop_constraint('unique_reservation_seat', 'reservation_seats', type_='unique')
    # ### end Alembic commands ###
