"""added time stamps in movies model

Revision ID: b7e379191b75
Revises: a154e8a5ad10
Create Date: 2026-10-01 12:02:20.164742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7e379191b75'
down_revision: Union[str, Sequence[str], None] = 'a154e8a5ad10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_reservation_seat'), 'reservation_seats', type_='unique')
    op.drop_constraint(op.f('seats_seat_label_key'), 'seats', type_='unique')
    op.create_unique_constraint('unique_seat_per_hall', 'seats', ['hall_id', 'seat_label'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_seat_per_hall', 'seats', type_='unique')
    op.create_unique_constraint(op.f('seats_seat_label_key'), 'seats', ['seat_label'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('unique_reservation_seat'), 'reservation_seats', ['reservation_id', 'seat_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
