"""intitialized database and relations

Revision ID: dcdae5953adc
Revises: 
Create Date: 2026-10-07 11:33:39.274125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcdae5953adc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('halls',
    sa.Column('hall_id', sa.UUID(), nullable=False),
    sa.Column('hall_name', sa.String(), nullable=False),
    sa.Column('hall_abbrv', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('hall_id'),
    sa.UniqueConstraint('hall_abbrv'),
    sa.UniqueConstraint('hall_name')
    )
    op.create_table('movies',
    sa.Column('movie_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('poster_image', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('movie_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('seats',
    sa.Column('seat_id', sa.UUID(), nullable=False),
    sa.Column('hall_id', sa.UUID(), nullable=False),
    sa.Column('seat_label', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['hall_id'], ['halls.hall_id'], ),
    sa.PrimaryKeyConstraint('seat_id'),
    sa.UniqueConstraint('hall_id', 'seat_label', name='unique_seat_per_hall')
    )
    op.create_table('showtimes',
    sa.Column('showtime_id', sa.UUID(), nullable=False),
    sa.Column('movie_id', sa.UUID(), nullable=False),
    sa.Column('hall_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ticket_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['hall_id'], ['halls.hall_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.movie_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('showtime_id'),
    sa.UniqueConstraint('hall_id', 'start_time', name='unique_showtime')
    )
    op.create_index(op.f('ix_showtimes_hall_id'), 'showtimes', ['hall_id'], unique=False)
    op.create_index(op.f('ix_showtimes_movie_id'), 'showtimes', ['movie_id'], unique=False)
    op.create_table('reservations',
    sa.Column('reservation_id', sa.UUID(), nullable=False),
    sa.Column('showtime_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_in', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['showtime_id'], ['showtimes.showtime_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('reservation_id')
    )
    op.create_table('reservation_seats',
    sa.Column('reservation_id', sa.UUID(), nullable=False),
    sa.Column('seat_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.reservation_id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.seat_id'], ),
    sa.PrimaryKeyConstraint('reservation_id', 'seat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation_seats')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_showtimes_movie_id'), table_name='showtimes')
    op.drop_index(op.f('ix_showtimes_hall_id'), table_name='showtimes')
    op.drop_table('showtimes')
    op.drop_table('seats')
    op.drop_table('users')
    op.drop_table('movies')
    op.drop_table('halls')
    # ### end Alembic commands ###
